### ISSUE TITLE
Xcode 16.0 Beta 1 - Build failure: unable to type-check in reasonable time

### ISSUE THREAD

**Issue by nicholaslythall** [nalexn/ViewInspector#307] opened 2024-06-11 03:46 UTC
When building the library with the  Xcode 16.0 Beta 1, it fails with the following error:

```
ViewSearchIndex.swift:444:13: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
            .init(count: sheetModifiers.count, { index -> UnwrappedView in
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Referencing this expression: https://github.com/nalexn/ViewInspector/blob/3f4f98dcff79ffd1eb530197f341c715595111b1/Sources/ViewInspector/ViewSearchIndex.swift#L458-L467

**Comment by ghost** [comment] 2024-06-11 05:57
I'm seeing this error too. I wonder if there are build options that can work around this in the meantime?

**Comment by KevinDoremy** [comment] 2024-06-18 01:00
Could it fix the problem ?

`let sheetModifiersViews = .init(count: sheetModifiers.count) { index -> UnwrappedView in
    try sheetModifiers[index].builder(parent, index)
}

let actionSheetModifiersViews = .init(count: actionSheetModifiers.count) { index -> UnwrappedView in
    try actionSheetModifiers[index].builder(parent, index)
}

let alertModifiersViews = .init(count: alertModifiers.count) { index -> UnwrappedView in
    try alertModifiers[index].builder(parent, index)
}

let popoverModifiersViews = .init(count: popoverModifiers.count) { index -> UnwrappedView in
    try popoverModifiers[index].builder(parent, index)
}

return sheetModifiersViews + actionSheetModifiersViews + alertModifiersViews + popoverModifiersViews`

**Comment by sisoje** [comment] 2024-06-26 12:06
> Could it fix the problem ?
> 
> ```swift
> let sheetModifiersViews = .init(count: sheetModifiers.count) { index -> UnwrappedView in
>     try sheetModifiers[index].builder(parent, index)
> }
> 
> let actionSheetModifiersViews = .init(count: actionSheetModifiers.count) { index -> UnwrappedView in
>     try actionSheetModifiers[index].builder(parent, index)
> }
> 
> let alertModifiersViews = .init(count: alertModifiers.count) { index -> UnwrappedView in
>     try alertModifiers[index].builder(parent, index)
> }
> 
> let popoverModifiersViews = .init(count: popoverModifiers.count) { index -> UnwrappedView in
>     try popoverModifiers[index].builder(parent, index)
> }
> 
> return sheetModifiersViews + actionSheetModifiersViews + alertModifiersViews + popoverModifiersViews
> ```

no, the .init is slow

**Comment by sisoje** [comment] 2024-06-26 12:07
> I'm seeing this error too. I wonder if there are build options that can work around this in the meantime?

point to some more recent commit hash?

**Comment by ghost** [comment] 2024-06-26 12:51
> > I'm seeing this error too. I wonder if there are build options that can work around this in the meantime?
> 
> point to some more recent commit hash?

Well yeah it looks to have been addressed in #308. Have stopped using Xcode 16 for the moment, but I'd have thought this would fix it

**Comment by cameroncooke** [comment] 2024-07-11 14:59
When do we think 0.10.0 might be released?

**Comment by nh7a** [comment] 2024-07-11 18:34
@nalexn can you release #308 as `0.9.12` so that we can use Xcode 16 to build ViewInspector, please? Since `0.10.0` is a breaking change and will require a lot of changes to existing code, I believe many people will need to stick with `0.9.11` for a while. But it doesn't build with Xcode 16 without #308.

**Comment by nalexn** [comment] 2024-07-12 08:36
> Since 0.10.0 is a breaking change and will require a lot of changes to existing code

Hold on, can you elaborate more on that? We've put extra effort into making sure there are little to no changes required when updating to this version! In the meanwhile, you can get yourself unblocked by forking the 0.9.2 and patching with #308

> When do we think 0.10.0 might be released?

I'm thinking to wait for Xcode 16 RC. The problem is that in the current Xcode 16 beta I'm seeing a strange abundance of `AnyView` being inserted all over the SwiftUI views's inner structures, this looks like a bug on Apple's side, but I won't be surprized if they keep it like that. If you're interested I'll share the details later

**Comment by cameroncooke** [comment] 2024-07-12 08:46
Yes I'm seeing AnyView too in fact some of my tests are failing as I'm now getting unexpected types. It's odd because I thought AnyView was poor for performance reasons so I'm surprised Apple is starting to use it everywhere. 

If it's a bug it's a weird one I mean how does that even happen. If it's not a bag what are the implications for this library can it be worked around?

**Comment by nalexn** [comment] 2024-07-12 09:06
Well, at first I tried to work around all those implicit AnyViews on the library side, but I could not easily find the pattern when they are being inserted, and worse than that, there was no way to confidently distinguish where it was `AnyView` used by the user vs `AnyView` inserted by compiler. So I gave up on this idea.

For now [there is a work around](https://github.com/nalexn/ViewInspector/issues/314#issuecomment-2216846324), and that's apparently how we'll need to address this issue

**Comment by cameroncooke** [comment] 2024-07-12 10:20
My failing tests were already using find:

```
struct CustomButtonType: View {
    var body: some View {
        Button(....)
            .buttonStyle(CustomButtonStyle())
    }
}
```

Now failing:
```swift
sut.inspect().find(CustomButtonType.self).button() // -> AnyView
```

**Comment by nalexn** [comment] 2024-07-12 10:48
Then it'd be `sut.inspect().find(CustomButtonType.self).find(ViewType.Button.self)`, or `.anyView().button()`, as now there is an `AnyView` wrapping the button

**Comment by cameroncooke** [comment] 2024-07-12 10:53
Will give that a try, thanks.

**Comment by nh7a** [comment] 2024-07-12 20:05
With `0.10.0`, the code below no longer builds, whether Xcode 15.4 or 16.0. And we use this pattern a lot.
```swift
func test_foo() async {  // Note: `async`
    let sut = ContentView()
    let exp = sut.inspection.inspect { view in  // 🔴 Call can throw, but it is not marked with 'try' and the error is not handled
        XCTAssertFalse(try view.actualView().flag)
        try view.button().tap()
        XCTAssertTrue(try view.actualView().flag)
    }
    ViewHosting.host(view: sut)
    await fulfillment(of: [exp], timeout: 0.1)  // 🔴 Cannot convert value of type '()' to expected element type 'Array<XCTestExpectation>.ArrayLiteralElement' (aka 'XCTestExpectation')
}
```

**Comment by nh7a** [comment] 2024-07-12 23:21
Okay, just tried patching #308 on `9.11.0` and confirmed it now successfully builds with Xcode 16. Nice. However, because of the known issue (random `AnyView()`), I saw hundreds of errors and crashes when I ran the tests. So, yeah, I'd agree it's useless and not worth exploring `9.12.0`.

**Comment by waitbutY** [comment] 2024-07-25 14:55
Any update on this issue? I think this is the only package impeding us from successfully running on XCode16.  I looked at the Beta 4 release notes, nothing stood out to me as a fix for the issues above

**Comment by nalexn** [comment] 2024-08-05 05:09
> Any update on this issue? I think this is the only package impeding us from successfully running on XCode16. I looked at the Beta 4 release notes, nothing stood out to me as a fix for the issues above

I spent half of this weekend tweaking and fixing what has changed in beta 4 since beta 2. There are tons of changes, often small, but sufficient to break stuff.

SPM allows you to pin to a branch rather than to a version, if you really need to use beta Xcode and ViewInspector - please pin to the 0.10.0 branch for now.

**Comment by tummalaguntimahesh** [comment] 2024-08-23 17:05
Looking for an update on this issue as it is blocking us from building in Xcode 16. 
Please let us know when this version is going to be published as we need to use a published version and can't point to any specific branch.
Issue - In Xcode 16 Beta, we are getting an error: **`"the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions"`**

**Comment by nalexn** [comment] 2024-08-23 17:09
@tummalaguntimahesh 
> please pin to the 0.10.0 branch for now.

**Comment by waitbutY** [comment] 2024-09-04 12:09
Sorry @nalexn one more question, is there a target date for `0.10.0` to be released?  Just when everything with `pending release` is merged?

**Comment by nalexn** [comment] 2024-09-04 12:28
@waitbutY shortly after stable release of Xcode 16.0 or 16.1, both are in beta still

**Comment by A30008910-wei** [comment] 2024-09-10 23:44
Xcode 16.0 RC is available now. 
https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes

**Comment by ghost** [comment] 2024-09-11 04:45
Xcode Cloud now defaults to using the Xcode 16 RC if set to "Latest stable version", so I'm now seeing this error there in automated test runs. Minor inconvenience to set the version to something else, but just fyi I'd imagine more people will encounter this error in CI pipelines now.

**Comment by cerupcat** [comment] 2024-09-16 19:14
Any updates on this?

**Comment by Ecarrion** [comment] 2024-09-16 21:36
FYI, Just tested this in the latest Xcode 16.0 Release(16A242d) and the issue persists.

**Comment by nh7a** [comment] 2024-09-16 22:18
@Ecarrion what issue? I see no issue in the building with Xcode 16 (16A242d) using `branch 0.10.0` at all.

**Comment by A30008910-wei** [comment] 2024-09-17 04:27
Xcode 16 is officially released https://developer.apple.com/xcode/
Any timeline on when `0.10.0` will be released?

**Comment by nalexn** [comment] 2024-09-17 10:27
v0.10.0 released

**Closed as completed by nalexn** 2024-09-17 10:27 UTC
