### ISSUE TITLE
Live Preview stops working when adding ViewInspector as a Swift Package

### ISSUE THREAD

**Issue by stuffmc** [nalexn/ViewInspector#89] opened 2021-03-05 17:57 UTC
```
Error Domain=FBProcessExit Code=128 "The process exited." UserInfo={NSLocalizedFailureReason=The process exited., BSErrorCodeDescription=other, NSUnderlyingError=0x600002dd4960 {Error Domain=dyld Code=1 "1" UserInfo={NSLocalizedFailureReason=1}}}

----------------------------------------

DyldLibraryLoadCrashError: MyApp crashed because XCTest.framework is missing

dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=~/Library/Developer/CoreSimulator/Caches/dyld/20D80/com.apple.CoreSimulator.SimRuntime.iOS-14-4.18D46
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=~/Library/Developer/Xcode/DerivedData/MyApp-cvjnhznhekfcltbnrfuotjfpcdol/Build/Intermediates.noindex/Previews/MyApp/Products/Debug-iphonesimulator
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/XCPreviewKit.framework/XCPreviewKit
DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks
DYL
  dyld: Using shared cache: 3337FA53-A445-3010-AF5C-1B11459F7C2E
Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/USER/Library/Developer/Xcode/UserData/Previews/Simulator Devices/96F28F43-DF0D-444C-89A1-FA2A4B5BB725/data/Containers/Bundle/Application/DDD7A2CD-B679-438B-A9B2-C6FC0E5F9317/MyApp.app/MyApp
  Reason: image not found

==================================

|  RemoteHumanReadableError: The operation couldn’t be completed. Transaction failed. Process failed to launch. (process launch failed)
|  
|  BSTransactionError (1):
|  ==transaction: <FBApplicationProcessLaunchTransaction: 0x600001afc000>
|  ==error-reason: process launch failed
|  ==NSLocalizedFailureReason: Transaction failed. Process failed to launch. (process launch failed)
|  ==precipitating-error: Error Domain=FBProcessExit Code=128 "The process exited." UserInfo={NSLocalizedFailureReason=The process exited., BSErrorCodeDescription=other, NSUnderlyingError=0x600002dd4960 {Error Domain=dyld Code=1 "1" UserInfo={NSLocalizedFailureReason=1}}}
|  ==error-description: Process failed to launch.
```

**Comment by stuffmc** [comment] 2021-03-05 22:08
FYI: For now, we found a way to add the Swift Package only for the test target, where the Live Preview doesn't run.

**Comment by nalexn** [comment] 2021-03-06 19:08
Interesting, I have several other people reporting issues around `XCTest.framework` - it's either "missing", or now it got linked for previews. I wonder if the recent Xcode updates changed the way the library gets added through SPM because there were no such issues for a year. I have a reference [sample project](https://github.com/nalexn/clean-architecture-swiftui) for which has ViewInspector added the normal way through SPM, and Previews work fine.

Please share how you managed to get around the error.

**Comment by copa** [comment] 2021-03-07 21:07
You can get around the error by selecting your test target while adding the package. Unfortunately afaik you can't change this later. In that case you need to re-add the package. 

<img width="729" alt="Screenshot 2021-03-07 at 22 03 51" src="https://user-images.githubusercontent.com/900594/110254808-0ffa9d00-7f91-11eb-9edc-9db51a03f01c.png">

**Comment by stuffmc** [comment] 2021-03-07 21:18
Worth filing a bug report @ Apple for that, @copa 
@nalexn: I'd still expect the library to not need that work around, but at least this ticket left open will give a workaround to people.

**Comment by patrickbdev** [comment] 2021-07-31 10:26
Can confirm that it isn't an issue with ViewInspector itself.
If you try adding `import XCTest` anywhere in your app target you'll get the following in the build log:
```
ld: warning: Could not find or use auto-linked library 'XCTestSwiftSupport'
ld: warning: Could not find or use auto-linked framework 'XCTest'
Undefined symbol: __swift_FORCE_LOAD_$_XCTestSwiftSupport
```
Maybe this is expected behaviour on Apple's part to not allow linking of XCTest to the app target.

Regardless I don't see a need to add ViewInspector to the app target and believe adding it to the Test target is correct and not a workaround.

@stuffmc are you happy to close this issue?

**Comment by orchetect** [comment] 2021-07-31 22:19
Could this be any way related to https://github.com/nalexn/ViewInspector/issues/122 ?

**Comment by nalexn** [comment] 2021-11-25 13:58
Closing this ticket as the symptoms of the incorrectly picked target [have changed](https://github.com/nalexn/ViewInspector/issues/146) in the newer Xcode versions. Although this was always [mentioned](https://github.com/nalexn/ViewInspector#how-do-i-add-it-to-my-xcode-project) in the readme, there will always be people not reading the manual 🤷‍♂️

**Closed by nalexn** 2021-11-25 13:58 UTC
